### ISSUE TITLE
Del-rapport

### ISSUE THREAD

**Issue by magnusqe** [Culf-B/DDU-projekt-1#8]
Skriv introduktion til vores emne og fokus samt hvordan vi ville gribe dette an.

- [x] Skriv om prototype(r)
- [x] Skriv om designspace
- [x] Lav forside
- [x] Indsæt links til Miro og GitHub
- [ ] Få feedback

**Comment by Culf-B** [comment]
Positiv feedback på det meste
Vi skal lige sørge for at ikke-valgte ideer fra idegenereringen kun er i bilag og valgte ide bliver "main character".
