### ISSUE TITLE
Rapport

### ISSUE THREAD

**Issue by magnusqe** [Culf-B/DDU-projekt-1#9]
Skriv en fyldestgørende rapport!
- [x] Sidehoved
- [x] Sidefod
- [x] Indledning
- [x] Brugt teori og tværfaglighed
- [x] Problemformulering
- [x] Problemafgrænsning og idéudvælgelse
- [x] Analyse
- [x] Projektstyring
- [x] Designprocessen
- [x] Refleksion og diskussion
- [x] Konklusion
- [x] Kildeliste
- [x] Bilag

**Comment by Culf-B** [comment]
woo den er afleveret
